### ISSUE TITLE
Dark Mode is not working

### ISSUE THREAD

**Issue by ajaynegi33** [ajaynegi45/Investment-Calculator#1]
when dark mode is activated You need to invest: text is not visible

**Comment by khushalmajoka** [comment]
<img width="844" alt="image" src="https://github.com/ajaynegi45/Investment-Calculator/assets/56840292/fa6b33a8-a017-4663-9bcb-ecab78c8bbb2">

I guess it is working fine. What's the issue?

**Comment by ajaynegi33** [comment]
@khushalmajoka 

when light mode is activated Everything works properly.
<img width="1106" alt="Screenshot 2023-10-05 at 2 35 52 PM" src="https://github.com/ajaynegi45/Investment-Calculator/assets/97536703/6c946971-d9b5-4591-a3d9-73cbda347ae1">

but in dark mode "You need to invest:"  text below the Calculate button is not visible


<img width="1074" alt="Screenshot 2023-10-05 at 2 36 00 PM" src="https://github.com/ajaynegi45/Investment-Calculator/assets/97536703/9a3aa2f4-fdfe-4a36-97ea-f4a61d11dbf3">

**Comment by khushalmajoka** [comment]
Okay got it, let me fix it.

**Comment by khushalmajoka** [comment]
@ajaynegi45 how do you locally run the project on you machine, because when I ran in the chrome I am not getting the option for light and dark mode.

<img width="960" alt="image" src="https://github.com/ajaynegi45/Investment-Calculator/assets/56840292/ac2969b3-f9bf-40eb-aa12-7db073d2a95d">

**Comment by ajaynegi33** [comment]
> @ajaynegi45 how do you locally run the project on you machine, because when I ran in the chrome I am not getting the option for light and dark mode.
> 
> <img alt="image" width="960" src="https://user-images.githubusercontent.com/56840292/272865071-ac2969b3-f9bf-40eb-aa12-7db073d2a95d.png">



Hi @khushalmajoka ,

I apologize for any inconvenience you experienced earlier. I'm pleased to inform you that I have worked on the issue you mentioned, and it has been fixed.

You can now try running the project locally again, and you should have the option to switch between light and dark modes. If you encounter any further issues or have additional questions while running the project, please don't hesitate to reach out. Your feedback is valuable to us, and we're here to assist you.

**Comment by khushalmajoka** [comment]
Thanks a lot @ajaynegi45

**Comment by khushalmajoka** [comment]
@ajaynegi45 There are still issues with the index.html file I guess, please check:

<img width="896" alt="image" src="https://github.com/ajaynegi45/Investment-Calculator/assets/56840292/f3722fa2-dc68-4597-9629-be534cc21e2e">

Also Dark mode option is available but still not working.

<img width="412" alt="image" src="https://github.com/ajaynegi45/Investment-Calculator/assets/56840292/b1c63da5-2408-4976-a256-d612d0589eb1">

**Comment by ankan-hazra-roni** [comment]
Hello [ajaynegi45](https://github.com/ajaynegi45), I have fixed this issue. Please do check.

**Comment by ajaynegi33** [comment]
> Hi @khushalmajoka ,
> 
> I apologize for any inconvenience you experienced earlier. I'm pleased to inform you that I have worked on the issue you mentioned, and it has been fixed.
> 
> You can now try running the project locally again, and you should have the option to switch between light and dark modes. If you encounter any further issues or have additional questions while running the project, please don't hesitate to reach out. Your feedback is valuable to us, and we're here to assist you.

Hi @khushalmajoka ,

I apologize for any inconvenience you experienced earlier. I'm pleased to inform you that I have worked on the issue you mentioned, and it has been fixed.

You can now try running the project locally again, and you should have the option to switch between light and dark modes. If you encounter any further issues or have additional questions while running the project, please don't hesitate to reach out. Your feedback is valuable to us, and we're here to assist you.

**Comment by ajaynegi33** [comment]
> Hello [ajaynegi45](https://github.com/ajaynegi45), I have fixed this issue. Please do check.

Not working

**Comment by khushalmajoka** [comment]
<img width="717" alt="image" src="https://github.com/ajaynegi45/Investment-Calculator/assets/56840292/c91fde56-5956-4de5-83f6-8491e09d910d">

**Comment by khushalmajoka** [comment]
@ajaynegi45 why have you closed the PR?? It fixes the issue very well.

**Comment by ajaynegi33** [comment]
> @ajaynegi45 why have you closed the PR?? It fixes the issue very well.

https://github.com/ajaynegi45/Investment-Calculator/pull/8#pullrequestreview-1661231192

**Comment by khushalmajoka** [comment]
Okay i can resolve this too. If you say I will?

**Comment by ajaynegi33** [comment]
> Okay i can resolve this too. If you say I will?

yes you can resolve this issue

**Comment by khushalmajoka** [comment]
Can u please reopen the PR?

**Comment by khushalmajoka** [comment]
or i will have ti create a new one.

**Comment by ajaynegi33** [comment]
> or i will have ti create a new one.

create new PR

**Comment by ajaynegi33** [comment]
You can checkout our more project to contribute [Library](https://github.com/ajaynegi45/Library)
